version: '2'
services:
  bkshkeycode-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/BkShKeyCode/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=BkShKeyCode
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
